### PR TITLE
1st pull request; fixes issues #4, #13, and #14.

### PR DESCRIPTION
**Pull request by arda-**
This pull fixes the following issues 
#4 - Restructuring files (50 points)
#13 - Special Characters feature doesn't affect generated password (50 points)
#14 - Implement JUnit testing. (100 points)

So far, the estimated amount of points completed in this pull is: **200 points**

### CODE REVIEW

**Comment by arda-** [comment]
As of today, the new commits also resolve:
#9 - Clean up GUI (100 points)
#18 - Restructuring/Refactoring old code (150 points)

the new total value of this pull is **450 points**.

**Comment by arda-** [comment]
Our work is complete! issue #11 is resolved (350 points), and follow-up issues have been created for next year's students. 

the new total value of this pull is **800 points**.

**Comment by PazZaitGivon** [comment]
wrong branch though

**Comment by arda-** [comment]
How so? this pulls asks to merge into UCSB-CS56-Projects:master. Should we be merging somewhere else instead?

**Comment by PazZaitGivon** [comment]
yeah, your branch; its ok though cause your lab06 kept track of all new changes so the lab06 pull to your branch took care of it

**Pull request closed without merging**
